name: Build on PR

on:
  pull_request:
    branches:
      - '**'  

jobs:
  continuous-integration:
    name: Building on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3  

      - name: Install Dependencies
        run: npm install --legacy-peer-deps  

      - name: Build
        run: npm run build
